import 'dotenv/config';
import path from 'path';
import { Season0endDate } from '../utils/data';
import { ArtSetting } from '../utils/types';
import { Address } from 'viem/accounts';

const baseSettings = {
  price: 0,
  maxSupply: undefined,
  soulbound: false,
  startDate: Math.floor(Date.now() / 1000),
  endDate: Season0endDate,
  artType: 'IMAGE' as const,
  externalURL: 'https://www.berachain.com/',
  description: 'For the pioneers ready to explore.',
  tags: ['Bera', 'Testnet'],
  artist: '0x5037e7747fAa78fc0ECF8DFC526DcD19f73076ce' as Address,
  receiver: '0x5037e7747fAa78fc0ECF8DFC526DcD19f73076ce' as Address,
};

export const artSettings: { [key: number]: ArtSetting } = {
  0: {
    ...baseSettings,
    name: 'Bera 2c',
    tags: ['Bera', 'Testnet', '2c'],
    imagePath: path.join(process.cwd(), 'public/assets/images/prod', '0.svg'),
  },
  1: {
    ...baseSettings,
    name: 'Bera 2d',
    tags: ['Bera', 'Testnet', '2d'],
    imagePath: path.join(process.cwd(), 'public/assets/images/prod', '1.svg'),
  },
  2: {
    ...baseSettings,
    name: 'Bera 2h',
    tags: ['Bera', 'Testnet', '2h'],
    imagePath: path.join(process.cwd(), 'public/assets/images/prod', '2.svg'),
  },
  3: {
    ...baseSettings,
    name: 'Bera 2s',
    tags: ['Bera', 'Testnet', '2s'],
    imagePath: path.join(process.cwd(), 'public/assets/images/prod', '3.svg'),
  },
  4: {
    ...baseSettings,
    name: 'Bera 3c',
    tags: ['Bera', 'Testnet', '3c'],
    imagePath: path.join(process.cwd(), 'public/assets/images/prod', '4.svg'),
  },
  5: {
    ...baseSettings,
    name: 'Bera 3d',
    tags: ['Bera', 'Testnet', '3d'],
    imagePath: path.join(process.cwd(), 'public/assets/images/prod', '5.svg'),
  },
  6: {
    ...baseSettings,
    name: 'Bera 3h',
    tags: ['Bera', 'Testnet', '3h'],
    imagePath: path.join(process.cwd(), 'public/assets/images/prod', '6.svg'),
  },
  7: {
    ...baseSettings,
    name: 'Bera 3s',
    tags: ['Bera', 'Testnet', '3s'],
    imagePath: path.join(process.cwd(), 'public/assets/images/prod', '7.svg'),
  },
  8: {
    ...baseSettings,
    name: 'Bera 4c',
    tags: ['Bera', 'Testnet', '4c'],
    imagePath: path.join(process.cwd(), 'public/assets/images/prod', '8.svg'),
  },
  9: {
    ...baseSettings,
    name: 'Bera 4d',
    tags: ['Bera', 'Testnet', '4d'],
    imagePath: path.join(process.cwd(), 'public/assets/images/prod', '9.svg'),
  },
  10: {
    ...baseSettings,
    name: 'Bera 4h',
    tags: ['Bera', 'Testnet', '4h'],
    imagePath: path.join(process.cwd(), 'public/assets/images/prod', '10.svg'),
  },
  11: {
    ...baseSettings,
    name: 'Bera 4s',
    tags: ['Bera', 'Testnet', '4s'],
    imagePath: path.join(process.cwd(), 'public/assets/images/prod', '11.svg'),
  },
  12: {
    ...baseSettings,
    name: 'Bera 5c',
    tags: ['Bera', 'Testnet', '5c'],
    imagePath: path.join(process.cwd(), 'public/assets/images/prod', '12.svg'),
  },
  13: {
    ...baseSettings,
    name: 'Bera 5d',
    tags: ['Bera', 'Testnet', '5d'],
    imagePath: path.join(process.cwd(), 'public/assets/images/prod', '13.svg'),
  },
  14: {
    ...baseSettings,
    name: 'Bera 5h',
    tags: ['Bera', 'Testnet', '5h'],
    imagePath: path.join(process.cwd(), 'public/assets/images/prod', '14.svg'),
  },
  15: {
    ...baseSettings,
    name: 'Bera 5s',
    tags: ['Bera', 'Testnet', '5s'],
    imagePath: path.join(process.cwd(), 'public/assets/images/prod', '15.svg'),
  },
  16: {
    ...baseSettings,
    name: 'Bera 6c',
    tags: ['Bera', 'Testnet', '6c'],
    imagePath: path.join(process.cwd(), 'public/assets/images/prod', '16.svg'),
  },
  17: {
    ...baseSettings,
    name: 'Bera 6d',
    tags: ['Bera', 'Testnet', '6d'],
    imagePath: path.join(process.cwd(), 'public/assets/images/prod', '17.svg'),
  },
  18: {
    ...baseSettings,
    name: 'Bera 6h',
    tags: ['Bera', 'Testnet', '6h'],
    imagePath: path.join(process.cwd(), 'public/assets/images/prod', '18.svg'),
  },
  19: {
    ...baseSettings,
    name: 'Bera 6s',
    tags: ['Bera', 'Testnet', '6s'],
    imagePath: path.join(process.cwd(), 'public/assets/images/prod', '19.svg'),
  },
  20: {
    ...baseSettings,
    name: 'Bera 7c',
    tags: ['Bera', 'Testnet', '7c'],
    imagePath: path.join(process.cwd(), 'public/assets/images/prod', '20.svg'),
  },
  21: {
    ...baseSettings,
    name: 'Bera 7d',
    tags: ['Bera', 'Testnet', '7d'],
    imagePath: path.join(process.cwd(), 'public/assets/images/prod', '21.svg'),
  },
  22: {
    ...baseSettings,
    name: 'Bera 7h',
    tags: ['Bera', 'Testnet', '7h'],
    imagePath: path.join(process.cwd(), 'public/assets/images/prod', '22.svg'),
  },
  23: {
    ...baseSettings,
    name: 'Bera 7s',
    tags: ['Bera', 'Testnet', '7s'],
    imagePath: path.join(process.cwd(), 'public/assets/images/prod', '23.svg'),
  },
  24: {
    ...baseSettings,
    name: 'Bera 8c',
    tags: ['Bera', 'Testnet', '8c'],
    imagePath: path.join(process.cwd(), 'public/assets/images/prod', '24.svg'),
  },
  25: {
    ...baseSettings,
    name: 'Bera 8d',
    tags: ['Bera', 'Testnet', '8d'],
    imagePath: path.join(process.cwd(), 'public/assets/images/prod', '25.svg'),
  },
  26: {
    ...baseSettings,
    name: 'Bera 8h',
    tags: ['Bera', 'Testnet', '8h'],
    imagePath: path.join(process.cwd(), 'public/assets/images/prod', '26.svg'),
  },
  27: {
    ...baseSettings,
    name: 'Bera 8s',
    tags: ['Bera', 'Testnet', '8s'],
    imagePath: path.join(process.cwd(), 'public/assets/images/prod', '27.svg'),
  },
  28: {
    ...baseSettings,
    name: 'Bera 9c',
    tags: ['Bera', 'Testnet', '9c'],
    imagePath: path.join(process.cwd(), 'public/assets/images/prod', '28.svg'),
  },
  29: {
    ...baseSettings,
    name: 'Bera 9d',
    tags: ['Bera', 'Testnet', '9d'],
    imagePath: path.join(process.cwd(), 'public/assets/images/prod', '29.svg'),
  },
  30: {
    ...baseSettings,
    name: 'Bera 9h',
    tags: ['Bera', 'Testnet', '9h'],
    imagePath: path.join(process.cwd(), 'public/assets/images/prod', '30.svg'),
  },
  31: {
    ...baseSettings,
    name: 'Bera 9s',
    tags: ['Bera', 'Testnet', '9s'],
    imagePath: path.join(process.cwd(), 'public/assets/images/prod', '31.svg'),
  },
  32: {
    ...baseSettings,
    name: 'Bera Tc',
    tags: ['Bera', 'Testnet', 'Tc'],
    imagePath: path.join(process.cwd(), 'public/assets/images/prod', '32.svg'),
  },
  33: {
    ...baseSettings,
    name: 'Bera Td',
    tags: ['Bera', 'Testnet', 'Td'],
    imagePath: path.join(process.cwd(), 'public/assets/images/prod', '33.svg'),
  },
  34: {
    ...baseSettings,
    name: 'Bera Th',
    tags: ['Bera', 'Testnet', 'Th'],
    imagePath: path.join(process.cwd(), 'public/assets/images/prod', '34.svg'),
  },
  35: {
    ...baseSettings,
    name: 'Bera Ts',
    tags: ['Bera', 'Testnet', 'Ts'],
    imagePath: path.join(process.cwd(), 'public/assets/images/prod', '35.svg'),
  },
  36: {
    ...baseSettings,
    name: 'Bera Jc',
    tags: ['Bera', 'Testnet', 'Jc'],
    imagePath: path.join(process.cwd(), 'public/assets/images/prod', '36.svg'),
  },
  37: {
    ...baseSettings,
    name: 'Bera Jd',
    tags: ['Bera', 'Testnet', 'Jd'],
    imagePath: path.join(process.cwd(), 'public/assets/images/prod', '37.svg'),
  },
  38: {
    ...baseSettings,
    name: 'Bera Jh',
    tags: ['Bera', 'Testnet', 'Jh'],
    imagePath: path.join(process.cwd(), 'public/assets/images/prod', '38.svg'),
  },
  39: {
    ...baseSettings,
    name: 'Bera Js',
    tags: ['Bera', 'Testnet', 'Js'],
    imagePath: path.join(process.cwd(), 'public/assets/images/prod', '39.svg'),
  },
  40: {
    ...baseSettings,
    name: 'Bera Qc',
    tags: ['Bera', 'Testnet', 'Qc'],
    imagePath: path.join(process.cwd(), 'public/assets/images/prod', '40.svg'),
  },
  41: {
    ...baseSettings,
    name: 'Bera Qd',
    tags: ['Bera', 'Testnet', 'Qd'],
    imagePath: path.join(process.cwd(), 'public/assets/images/prod', '41.svg'),
  },
  42: {
    ...baseSettings,
    name: 'Bera Qh',
    tags: ['Bera', 'Testnet', 'Qh'],
    imagePath: path.join(process.cwd(), 'public/assets/images/prod', '42.svg'),
  },
  43: {
    ...baseSettings,
    name: 'Bera Qs',
    tags: ['Bera', 'Testnet', 'Qs'],
    imagePath: path.join(process.cwd(), 'public/assets/images/prod', '43.svg'),
  },
  44: {
    ...baseSettings,
    name: 'Bera Kc',
    tags: ['Bera', 'Testnet', 'Kc'],
    imagePath: path.join(process.cwd(), 'public/assets/images/prod', '44.svg'),
  },
  45: {
    ...baseSettings,
    name: 'Bera Kd',
    tags: ['Bera', 'Testnet', 'Kd'],
    imagePath: path.join(process.cwd(), 'public/assets/images/prod', '45.svg'),
  },
  46: {
    ...baseSettings,
    name: 'Bera Kh',
    tags: ['Bera', 'Testnet', 'Kh'],
    imagePath: path.join(process.cwd(), 'public/assets/images/prod', '46.svg'),
  },
  47: {
    ...baseSettings,
    name: 'Bera Ks',
    tags: ['Bera', 'Testnet', 'Ks'],
    imagePath: path.join(process.cwd(), 'public/assets/images/prod', '47.svg'),
  },
  48: {
    ...baseSettings,
    name: 'Bera Ac',
    tags: ['Bera', 'Testnet', 'Ac'],
    imagePath: path.join(process.cwd(), 'public/assets/images/prod', '48.svg'),
  },
  49: {
    ...baseSettings,
    name: 'Bera Ad',
    tags: ['Bera', 'Testnet', 'Ad'],
    imagePath: path.join(process.cwd(), 'public/assets/images/prod', '49.svg'),
  },
  50: {
    ...baseSettings,
    name: 'Bera Ah',
    tags: ['Bera', 'Testnet', 'Ah'],
    imagePath: path.join(process.cwd(), 'public/assets/images/prod', '50.svg'),
  },
  51: {
    ...baseSettings,
    name: 'Bera As',
    tags: ['Bera', 'Testnet', 'As'],
    imagePath: path.join(process.cwd(), 'public/assets/images/prod', '51.svg'),
  },
};
